### ISSUE TITLE
review if is right ?

### ISSUE THREAD

**Issue by sanchojaf** [openjaf/cenit#84]
review if is right  the next method?

https://github.com/openjaf/cenit/blob/develop/lib/mongoff/record.rb#L36

    def save(options={})
      if errors.blank?
        errors.add(:base, "Save operation not supported on not loaded data type #{orm_model.data_type.title}")
      end
      false
    end

maybe should be 

    def save(options={})
      if errors.present?
        errors.add(:base, "Save operation not supported on not loaded data type #{orm_model.data_type.title}")
         return false
      end
      true
    end

**Comment by macarci** [comment]
The method is not right but it is not wrong. The save method on Mongoff records should save the record in a compatible way with Mongoid, but this is not yet implemented so the method always fails by returning false an report an error if errors.blank? These behavior prevents the use of these method until the a proper implementation is supplied.
