### ISSUE TITLE
never will be raise exception

### ISSUE THREAD

**Issue by sanchojaf** [openjaf/cenit#91]
In https://github.com/openjaf/cenit/blob/develop/app/models/setup/build_in_data_type.rb

many methods have the next sintaxis

     if fields.present?
        raise Exception.new('Illegal argument') if fields.empty?
...

In this code never will be sent and exception, because if fields.present? is true exclude the possibility of  fields.empty? should be true

**Comment by macarci** [comment]
The code is correct. The field fields should be present to check if its an empty collection, so the exception is raised when the fields collection is empty but theses is checked only if fields is present, i.e, it is not the nil value.

**Comment by sanchojaf** [comment]
Is not right, because present? == !blank? and (blank? == true) <=> (nil? || empty?).
